output_dir: outputs
output_format: json
#output_format: md
mt5_files_dir: /mnt/c/Users/anael/AppData/Roaming/MetaQuotes/Terminal/38FF261A42172F3478E54D3A1A8FE02B/MQL5/Files
tickers_endpoint: http://127.0.0.1:5678/webhook/get-tickers

sites:
  fundamentus_insiders:
    enabled: true
    tipo: 1
  fundamentus_acionistas:
    enabled: true
    tipo: 1
  bestchoice_volume:
    enabled: true
  bestchoice_magic_formula:
    enabled: true
  statusinvest_prices:
    enabled: true
    cookie:
    storage_state_path: statusinvest_storage_state.json
    use_browser_fallback: true
